language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: D/rkM9HdivqiltPlXWwG2yBacvdlEjljGbaLkgc6jRX2at8wj0hzNzeHIpW+f+vZUlg6Ki+BgjQ7fIM25e38DsH74+3xS6HZFkTh6V7PXQ3BxaUpx09Z4Fv4ARgfhklG/Rq+MRoCBqDSCmGMt8mp4m+OQyrFCu+tB+hpWUcgDbidU8t5UMGljYCx29iTBV6WRhECLvq1djB8KHE8fPV6ys74Q8cKO1LyeK1htl7F6uPmpFjwj12s/KwKvjOPB6j3Dxi2TOG0qJPawk95hYwzvdz7UwTEjTS+wp/7IfKqeAHyvzTTUCuSw1+B6vFOWydrAqHM3O1izGz4NxdoTHE/psn2cjQ7RTGnxYed5Lpc0kLzlIge4QeSbrQXaWDvBce71Im4gMyjFYu31Lxa9rbEVH9skoGk5XTcBSYCqKlkAHkF8JZqSo+khqMvE9ad5HGneifKTlJEQRXlyvApwJ7AyTmZZEGpz5Q5oIfuVqLICjxTEfjIZZHaBssvuwR72XwiiVD7YzG2Pc6LeJT0m/f2L/oWUTYY1sSzlRHoO40KGKr/d+LWvIb58RE3pti8/J7AwRaYSx00LcrKobBFzg8AnFP8NiIkEzvuPi3Z/zsQ7e2ZD/mZWbVJStRQRGWuWngXSuquEb08KN+SqZYsZkrxPAyyMPlq702FpwzTjR/fWjQ=
  - secure: IQtIv2TaXa8HeMRriEhItufRWHFQrFhvhHcZlNSDTdnfC4uMHxG/gGc1Bn691GcZ8uWnnglljC/YAzrW3QPwzBjmRN+FYddaHUgXnTP5akv/wC7RvshGpVFeJFG7KLlPyLWis8Xo71L0mh7XMWIONbmneUMeiNg21dPtTr6i2I99HSvgviEp+C7LBHElY7kS+KO7MKEM0N73rMDHuug6wuBK6sTQI0Vd5REUc0s/aW349UM8LtX/raMzjeLzBgYIFhb3iy0Dgi52Irw7l8U0Gf6IvP+y1yCla76n1lGjuNjbnD8MOt//1NSONVEtqztno/MI+Cz2A8069xSMoEzRFRO/q5DCaUjUm9rHhNE+Qdqg7+ndGC38gn/NNfa6XuaIwtqRZqVgUgJ0/+hkiZyqdjxYswVIyEqzW0vr/GdCtLAhbnBgBCZAjuJw3jFEPJ9280dVhrNSYjOOzSWlfrfDaohnZxADGbSfTcazAUhaFCk4zQF5O3HT4X32oJtaCEaDkrgYAjHIPoEujrbi2+J50erGrlQJqFY/ZgGlgWv2GEfsJVsbHhZ11hcKSkPcsg04B9duCYcLumaLKpZ+90MT7WT7zGK2QKVITT+Sck69aAPJQAub4RUywEke7MSTi+0KrRsBbLUS311iy+ogoSKc4eCrHDi34aqpBV/RHMSroDI=
